apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ha0e8k7mq-nodejs 
  janus-idp.io/tekton: ha0e8k7mq-nodejs
  backstage.io/kubernetes-id: ha0e8k7mq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ha0e8k7mq-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml