apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ha0e8k7mq-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ha0e8k7mq-nodejs 
  name: ha0e8k7mq-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ha0e8k7mq-nodejs 
